"""db_setup

Revision ID: 7fb9b25cb2d4
Revises: 
Create Date: 2026-04-04 16:24:30.243520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7fb9b25cb2d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS auth"))
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS loco"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'dispatcher', 'driver', 'viewer', name='user_role', schema='auth'), server_default=sa.text("'viewer'::auth.user_role"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='auth'
    )
    op.create_table('locomotives',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'maintenance', 'idle', 'decommissioned', name='locomotive_status', schema='loco'), server_default=sa.text("'idle'::loco.locomotive_status"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='loco'
    )
    op.create_index('idx_locomotives_code', 'locomotives', ['code'], unique=False, schema='loco')
    op.create_index('idx_locomotives_status', 'locomotives', ['status'], unique=False, schema='loco')
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('table_name', sa.String(length=64), nullable=True),
    sa.Column('record_id', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index('idx_audit_log_created_at', 'audit_log', [sa.literal_column('created_at DESC')], unique=False, schema='auth')
    op.create_index('idx_audit_log_user_id', 'audit_log', ['user_id'], unique=False, schema='auth')
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='auth'
    )
    op.create_index('idx_sessions_expires_at', 'sessions', ['expires_at'], unique=False, schema='auth')
    op.create_index('idx_sessions_token_hash', 'sessions', ['token_hash'], unique=False, schema='auth')
    op.create_index('idx_sessions_user_id', 'sessions', ['user_id'], unique=False, schema='auth')
    op.create_table('alert_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('locomotive_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='severity_enum', schema='loco'), nullable=False),
    sa.Column('source_metric', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['locomotive_id'], ['loco.locomotives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='loco'
    )
    op.create_index('idx_alert_events_active', 'alert_events', ['locomotive_id', 'is_active'], unique=False, schema='loco', postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_alert_events_loco_ts', 'alert_events', ['locomotive_id', sa.literal_column('ts DESC')], unique=False, schema='loco')
    op.create_table('fault_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('locomotive_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fault_code', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='severity_enum', schema='loco'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['locomotive_id'], ['loco.locomotives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='loco'
    )
    op.create_index('idx_fault_events_active', 'fault_events', ['locomotive_id', 'is_active'], unique=False, schema='loco', postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_fault_events_code', 'fault_events', ['fault_code'], unique=False, schema='loco')
    op.create_index('idx_fault_events_loco_ts', 'fault_events', ['locomotive_id', sa.literal_column('ts DESC')], unique=False, schema='loco')
    op.create_table('index_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('min_normal', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_normal', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('warning_threshold', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('critical_threshold', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), server_default=sa.text('1.0'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('weight >= 0 AND weight <= 1', name='index_settings_weight_check'),
    sa.ForeignKeyConstraint(['updated_by'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_name'),
    schema='loco'
    )
    op.create_table('telemetry_current',
    sa.Column('locomotive_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('speed', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fuel_level', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('battery_voltage', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('traction_current', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('brake_pressure', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('engine_temp', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('vibration_level', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('signal_quality', sa.SmallInteger(), nullable=True),
    sa.Column('health_index', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('health_status', sa.Enum('normal', 'attention', 'critical', 'unknown', name='health_status_enum', schema='loco'), server_default=sa.text("'unknown'::loco.health_status_enum"), nullable=False),
    sa.CheckConstraint('health_index >= 0 AND health_index <= 100', name='telemetry_current_health_index_check'),
    sa.CheckConstraint('signal_quality >= 0 AND signal_quality <= 100', name='telemetry_current_signal_quality_check'),
    sa.ForeignKeyConstraint(['locomotive_id'], ['loco.locomotives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('locomotive_id'),
    schema='loco'
    )
    op.create_table('telemetry_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('locomotive_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('speed', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fuel_level', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('battery_voltage', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('traction_current', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('brake_pressure', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('engine_temp', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('vibration_level', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('signal_quality', sa.SmallInteger(), nullable=True),
    sa.Column('health_index', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('health_status', sa.Enum('normal', 'attention', 'critical', 'unknown', name='health_status_enum', schema='loco'), server_default=sa.text("'unknown'::loco.health_status_enum"), nullable=False),
    sa.CheckConstraint('health_index >= 0 AND health_index <= 100', name='telemetry_snapshots_health_index_check'),
    sa.CheckConstraint('signal_quality >= 0 AND signal_quality <= 100', name='telemetry_snapshots_signal_quality_check'),
    sa.ForeignKeyConstraint(['locomotive_id'], ['loco.locomotives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='loco'
    )
    op.create_index('idx_ts_snapshots_loco_ts', 'telemetry_snapshots', ['locomotive_id', sa.literal_column('ts DESC')], unique=False, schema='loco')
    op.create_index('idx_ts_snapshots_ts', 'telemetry_snapshots', [sa.literal_column('ts DESC')], unique=False, schema='loco')
    op.create_table('health_factor_breakdown',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('locomotive_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('contribution_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['locomotive_id'], ['loco.locomotives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['loco.telemetry_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='loco'
    )
    op.create_index('idx_hfb_loco_ts', 'health_factor_breakdown', ['locomotive_id', sa.literal_column('ts DESC')], unique=False, schema='loco')
    op.create_index('idx_hfb_snapshot_id', 'health_factor_breakdown', ['snapshot_id'], unique=False, schema='loco')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hfb_snapshot_id', table_name='health_factor_breakdown', schema='loco')
    op.drop_index('idx_hfb_loco_ts', table_name='health_factor_breakdown', schema='loco')
    op.drop_table('health_factor_breakdown', schema='loco')
    op.drop_index('idx_ts_snapshots_ts', table_name='telemetry_snapshots', schema='loco')
    op.drop_index('idx_ts_snapshots_loco_ts', table_name='telemetry_snapshots', schema='loco')
    op.drop_table('telemetry_snapshots', schema='loco')
    op.drop_table('telemetry_current', schema='loco')
    op.drop_table('index_settings', schema='loco')
    op.drop_index('idx_fault_events_loco_ts', table_name='fault_events', schema='loco')
    op.drop_index('idx_fault_events_code', table_name='fault_events', schema='loco')
    op.drop_index('idx_fault_events_active', table_name='fault_events', schema='loco', postgresql_where=sa.text('is_active = true'))
    op.drop_table('fault_events', schema='loco')
    op.drop_index('idx_alert_events_loco_ts', table_name='alert_events', schema='loco')
    op.drop_index('idx_alert_events_active', table_name='alert_events', schema='loco', postgresql_where=sa.text('is_active = true'))
    op.drop_table('alert_events', schema='loco')
    op.drop_index('idx_sessions_user_id', table_name='sessions', schema='auth')
    op.drop_index('idx_sessions_token_hash', table_name='sessions', schema='auth')
    op.drop_index('idx_sessions_expires_at', table_name='sessions', schema='auth')
    op.drop_table('sessions', schema='auth')
    op.drop_index('idx_audit_log_user_id', table_name='audit_log', schema='auth')
    op.drop_index('idx_audit_log_created_at', table_name='audit_log', schema='auth')
    op.drop_table('audit_log', schema='auth')
    op.drop_index('idx_locomotives_status', table_name='locomotives', schema='loco')
    op.drop_index('idx_locomotives_code', table_name='locomotives', schema='loco')
    op.drop_table('locomotives', schema='loco')
    op.drop_table('users', schema='auth')
    op.execute(sa.text("DROP SCHEMA IF EXISTS loco CASCADE"))
    op.execute(sa.text("DROP SCHEMA IF EXISTS auth CASCADE"))
    # ### end Alembic commands ###
